FROM node:16.13.0

RUN apk add --no-cache python2 g++ make

# set variables
ENV HOME_ROOT=/opt/app-root
ENV HOME=/opt/app-root/src

RUN mkdir -p $HOME

WORKDIR $HOME_ROOT

WORKDIR $HOME

COPY . .

# If you are building your code for production
# RUN npm install --only=production
# RUN npm set progress=false
RUN npm install

# run the database migrations and seeding
CMD [ "npm", "run", "export" ]
